server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

#
  cloud:
    gateway:
      routes:

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:9094/eureka

