server:
  port: 8080
spring.cloud.stream:
  function:
    definition: supplier;consumer
  bindings:
    supplier-out-0:
      destination: order-created
    consumer-in-0:
      destination: order-updated
#spring:
#  jpa:
##    defer-datasource-initialization: true
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console.enabled: true
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: abc
#    password: abc
#    driverClassName: org.h2.Driver


spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver